---
title: pg_partition_templates
---

<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

The `pg_partition_templates` system view is used to show the subpartitions that were created using a subpartition template.

<a id="topic1__hd179967"></a>
<span class="tablecap">Table 1. pg\_catalog.pg\_partition\_templates</span>


| column                    | type     | references | description                                                                                                                                                                                                      |
|---------------------------|----------|------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `schemaname`              | name     |            | The name of the schema the partitioned table is in.                                                                                                                                                              |
| `tablename`               | name     |            | The table name of the top-level parent table.                                                                                                                                                                    |
| `partitionname`           | name     |            | The name of the subpartition (this is the name to use if referring to the partition in an `ALTER TABLE` command). `NULL` if the partition was not given a name at create time or generated by an `EVERY` clause. |
| `partitiontype`           | text     |            | The type of subpartition (range or list).                                                                                                                                                                        |
| `partitionlevel`          | smallint |            | The level of this subpartition in the hierarchy.                                                                                                                                                                 |
| `partitionrank`           | bigint   |            | For range partitions, the rank of the partition compared to other partitions of the same level.                                                                                                                  |
| `partitionposition`       | smallint |            | The rule order position of this subpartition.                                                                                                                                                                    |
| `partitionlistvalues`     | text     |            | For list partitions, the list value(s) associated with this subpartition.                                                                                                                                        |
| `partitionrangestart`     | text     |            | For range partitions, the start value of this subpartition.                                                                                                                                                      |
| `partitionstartinclusive` | boolean  |            | `T` if the start value is included in this subpartition. `F` if it is excluded.                                                                                                                                  |
| `partitionrangeend`       | text     |            | For range partitions, the end value of this subpartition.                                                                                                                                                        |
| `partitionendinclusive`   | boolean  |            | `T` if the end value is included in this subpartition. `F` if it is excluded.                                                                                                                                    |
| `partitioneveryclause`    | text     |            | The `EVERY` clause (interval) of this subpartition.                                                                                                                                                              |
| `partitionisdefault`      | boolean  |            | `T` if this is a default subpartition, otherwise `F`.                                                                                                                                                            |
| `partitionboundary`       | text     |            | The entire partition specification for this subpartition.                                                                                                                                                        |



